### ISSUE TITLE
zxcvbn throws OverflowError

### ISSUE THREAD

**Issue by vanadium23** [dwolfhub/zxcvbn-python#11]
Hello, fellows.

I found out, that for some looong text zxcvbn throws OverflowError.
Code example:

```
import string
import random
from zxcvbn import zxcvbn

text = ''.join([random.choice(string.ascii_letters) for _ in range(310)])
zxcvbn(text)
```

Don't know if it needs to be clear in docs, or some hack for long text input or rewrite math operations to `Decimal`?

**Comment by dwolfhub** [comment]
Thanks for pointing this out. I'll run some tests on my end. 

Really, depending on your hardware, at a certain point this will happen. There is not much we can do about it other than warn people about an arbitrary limit.

Maybe there are things I can do to raise that limit, I'll have a look.
