### ISSUE TITLE
DeprecationWarning on Python 3.6

### ISSUE THREAD

**Issue by rudolphfroger** [dwolfhub/zxcvbn-python#20]
The following warning is shown when using Python 3.6:

`WARNING (py.warnings#99) zxcvbn/scoring.py:282: DeprecationWarning: invalid escape sequence \d
    if re.compile('\d').match(first_chr):`

This is easily solved by prepending these string literals with a 'r':

`    if re.compile(r'\d').match(first_chr):`

**Comment by dwolfhub** [comment]
resolved in v4.4.20

thanks for the report!
