### ISSUE TITLE
user_inputs argument

### ISSUE THREAD

**Issue by NoName115** [dwolfhub/zxcvbn-python#26]
I think that 'user\_inputs' argument is not working correctly, e.g.
```python
>>> from zxcvbn import zxcvbn
>>> zxcvbn('i love you')['score']
3
>>> zxcvbn('i love you', user_inputs=['love'])['score']
3
>>> zxcvbn('i love you', user_inputs=['love', 'you'])['score']
3
>>> zxcvbn('i love you', user_inputs=['i', 'love', 'you'])['score']
3
```

**Comment by dwolfhub** [comment]
Hi! 

The functionality of this library is not my own. It's built to be a 100% compliant python port of the javascript library [here](https://github.com/dropbox/zxcvbn).

As you can see, the javascript library has the same results:

```
zxcvbn('i love you')['score']
3
zxcvbn('i love you', user_inputs=['love'])['score']
3
zxcvbn('i love you', user_inputs=['love', 'you'])['score']
3
zxcvbn('i love you', user_inputs=['i', 'love', 'you'])['score']
3
```

If you feel the behavior of the library has an error in it, please file a ticket in that repository.

Thanks!

**Comment by funkyfuture** [comment]
imo there are some problems here:

as far as i understand [this test](https://github.com/dropbox/zxcvbn/blob/67c4ece9efc40c9d0a1d7d995b2b22a91be500c2/test/test-matching.coffee#L189-L197) it seems that this implementation behaves differently. when i try the example with the Python implementation, i don't get any error message related to the user input.

given the age of both projects it may not be feasible to touch any of it, but at least a clear warning in the docs should make users aware to not rely on this feature. given that most uses of the lib have a security dimension, this is certainly helpful.
