### ISSUE TITLE
Add comparison to dropbox/python-zxcvbn

### ISSUE THREAD

**Issue by Lucas-C** [dwolfhub/zxcvbn-python#3]
Hi.

Could you please add in the README a comparison between this project and https://github.com/dropbox/python-zxcvbn ?

**Comment by dwolfhub** [comment]
Is there something specific you needed to know? That project has been abandoned for the last 4 years and as such is not up to date with the original library (https://github.com/dropbox/zxcvbn). The original library lists _this_ project as the official Python port in their README.

**Comment by Lucas-C** [comment]
That's all I needed. It may be useful to mention that in the README still.
Thanks

**Comment by dwolfhub** [comment]
Sure, I understand the confusion. I'll think about a good way to word that.
