### ISSUE TITLE
release transitional package to zxcvbn-python on PyPI

### ISSUE THREAD

**Issue by graingert** [dwolfhub/zxcvbn-python#33]
should be v5, containing only a setup.py that prints a deprecation warning and depends on 'zxcvbn'

**Comment by dwolfhub** [comment]
i was unsure how to handle the transition. happy to hear any ideas.

however, the latest v4 version should be showing a deprecation warning. any reason to bump to v5  for that? remember, that tag needs to be added to this github repo, and it's shared by both pip packages.

**Comment by dwolfhub** [comment]
closing now, but let me know if you have any more input on this. i released a version that supports universal wheels, thanks for the help on that.
