### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by di** [dwolfhub/zxcvbn-python#34]
I haven't been able to reproduce yet, but one of our users selected a password that generated an OverflowError in `zxcvbn`:

```
OverflowError: int too large to convert to float
  ...
  File "warehouse/forms.py", line 60, in __call__
    results = zxcvbn(field.data, user_inputs=user_inputs)
  File "zxcvbn/__init__.py", line 31, in zxcvbn
    result = scoring.most_guessable_match_sequence(password, matches)
  File "zxcvbn/scoring.py", line 200, in most_guessable_match_sequence
    bruteforce_update(k)
  File "zxcvbn/scoring.py", line 160, in bruteforce_update
    update(m, l + 1)
  File "zxcvbn/scoring.py", line 117, in update
    pi *= optimal['pi'][m['i'] - 1][l - 1]
```

**Comment by lodow** [comment]
When I use this string I get the same error :

> weopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioejiojweopiopdsjmkldjvoisdjfioej

If you remove the last character you won't get it.
The size is not fixed, it depends of the character used in your string.

Another example would be :
>ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ßèß*±¥®¥®ç¼Ø%ß®Î®ù×ß®ç¼Ø%ß®Î®®ç¼Ø%ß®Î®®ç¼Ø%e®Î®bdj®ç¼Ø%ß®Î®feuihfwdjnkjwuhcenjkehfuwihefuencwkjdnwenfkjwenfkje

Same thing, if you remove the last character you won't get the error.
