### ISSUE TITLE
Incorrect strength detection for password with spaces

### ISSUE THREAD

**Issue by gnomeby** [dwolfhub/zxcvbn-python#45]
Use common password with spaces around: " horse "
We get only bruteforce pattern in sequence and score == 2
{'pattern': 'bruteforce', 'token': ' horse ', 'i': 0, 'j': 6, 'guesses': 10000000, 'guesses_log10': 7.0}

**Comment by dwolfhub** [comment]
Hey @gnomeby,

The goal of this project is to match the results from the javascript library. Part of our test suite includes testing the results of 1M passwords to make sure they return the same results as the javascript library. So – are you seeing different results in the javascript library or is this, in your mind, a logic issue that both libraries have?

If it's the former, let me know and I'll add this specific password to the list of those we test. If the latter, you should file a bug in the javascript library. When it gets fixed over there I'll do the same.

Thanks!

**Comment by gnomeby** [comment]
You are right. Original library has the same problem:
https://github.com/dropbox/zxcvbn/issues/216
