### ISSUE TITLE
Useful feature unreleased

### ISSUE THREAD

**Issue by comradesmith** [dwolfhub/zxcvbn-python#46]
Hi, thanks to all contributors for writing this, its made a great password checker accessible to me as a python dev.

My only issue right now is that it has been a while since release [v4.4.27](https://github.com/dwolfhub/zxcvbn-python/releases/tag/v4.4.27) and since then there haven't been many releases. I think the feature merged in #43 would be really great to be released.

Are there upcoming release plans?

**Comment by dwolfhub** [comment]
Thanks for the kind words. This was an oversight on my part. Thanks for letting me know. I’ll push a new release later today 👍🏻

**Comment by dwolfhub** [comment]
v4.4.28 is now available. thanks again for the heads up!
