### ISSUE TITLE
4.4.28 tag is missing compared to PyPI

### ISSUE THREAD

**Issue by jbeich** [dwolfhub/zxcvbn-python#47]
Was it actually released? If so what commit the release corresponds to? I'm curious whether to package it downstream.

https://pypi.org/project/zxcvbn/4.4.28/
https://repology.org/project/python:zxcvbn/versions

**Comment by dwolfhub** [comment]
the tag didn't get pushed to github. i could have sworn i verified that...

can you make sure it looks ok on your end now?

**Comment by jbeich** [comment]
Thanks. [Works fine](https://github.com/freebsd/freebsd-ports/commit/9a1773556287f185f6ed07122a4be83f328ccd60) now.
