### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by rudolphfroger** [dwolfhub/zxcvbn-python#5]
It would be nice if the data files would be configurable to allow for word lists from other languages. It would also be nice if the feedback strings would be enclosed in gettext calls to allow for translations.

Would you consider changes to accommodate internationalization?

**Comment by dwolfhub** [comment]
Great ideas!

Using `gettext` would be an easy change. I'd need to think through how to configure word lists and it may require a minor version bump.

**Comment by dwolfhub** [comment]
I'm reading up on gettext to make sure I'm doing this correctly. Would you say it makes sense to call `bindtextdomain('zxcvbn')` to create a domain for this library by itself? or to not set a domain at all?

**Comment by dwolfhub** [comment]
Also see #8. Let me know if you run into any issues.

Thanks again!

**Comment by rudolphfroger** [comment]
Wow, that's exactly what I had in mind and I was just about to propose to write a patch for you.

Thanks a lot!
