### ISSUE TITLE
Feature Request: Pass in list of passwords, get list of scores back

### ISSUE THREAD

**Issue by clr2of8** [dwolfhub/zxcvbn-python#51]
I'm using zxcvbn on large lists (~70K) of passwords and calling zxcvbn individually this many times is very slow. I would like to pass in a list of passwords and get a list of scores back. Thank you

**Comment by dwolfhub** [comment]
Hey @clr2of8 
This project really aims to create feature parity with dropbox/zxcvbn, so we likely won't be adding new features. I'd be open to seeing a pull request, but I'm unclear how that will fix your problem, you'll still need to do the calculations for each password. Have you tried using threads or similar?
