### ISSUE TITLE
License file is missing from tarball

### ISSUE THREAD

**Issue by cvubrugier** [dwolfhub/zxcvbn-python#54]
## Summary

The license file is missing from the release tarball. This prevents some embedded distribution tools to perform their license compliance check. Adding the license file to the tarball would fix the issue.

## Additional context

I am integrating the python-zxcvbn package in an embedded device whose firmware is built with [Yocto](https://www.yoctoproject.org/). As you may know, Yocto is a collection of tools to build a custom Linux distribution for an embedded device.

Yocto helps with [license compliance verification](https://www.yoctoproject.org/docs/3.1.1/dev-manual/dev-manual.html#maintaining-open-source-license-compliance-during-your-products-lifecycle) by tracking the license file in the sources and verifying that the terms of the license have not changed (with checksums).

Because the license file is missing from the source tarball downloadable from [PyPI](https://pypi.org/project/zxcvbn-python/), Yocto cannot perform the license compliance check.

If you agree, I can provide a patch to add the `LICENSE.txt` file to the tarball.

**Comment by dwolfhub** [comment]
@cvubrugier a PR would be most welcome!
